apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: goat-statefulset
spec:
  selector:
    matchLabels:
      app: goat
  serviceName: "goat-service"
  replicas: 1
  template:
    metadata:
      labels:
        app: goat
    spec:
      volumes:
        - name: goat-data
          persistentVolumeClaim:
            claimName: goat-data-claim
      containers:
        - name: goat
          image: lnadev/goat-counter
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: goat-data
              mountPath: /goatcounter/db 
          env:
            - name: GOATCOUNTER_DOMAIN
              value: goat.lna-dev.net
            - name: GOATCOUNTER_EMAIL
              value: lukas.lna-dev.net
            - name: GOATCOUNTER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: goat-secrets
                  key: GOATCOUNTER_PASSWORD

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: goat-data-claim
spec:
  storageClassName: goat-data-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: goat-data-volume
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880" # 48 hours in minutes

---
apiVersion: v1
kind: Service
metadata:
  name: goat-service
spec:
  selector:
    app: goat
  ports:
    - port: 80
      targetPort: port-http
      name: http

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: goat-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: default-redirectscheme@kubernetescrd
spec:
  tls:
    - hosts:
        - "goat.lna-dev.net"
      secretName: goat-cert
  rules:
    - host: goat.lna-dev.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: goat-service
                port:
                  number: 80

---
# Needed because of HTTP to HTTPS redirecting
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: goat-ingress-http
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: default-redirectscheme@kubernetescrd
spec:
  rules:
    - host: goat.lna-dev.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: goat-service
                port:
                  number: 80

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirectscheme
spec:
  redirectRegex:
    regex: '^https?://(?:www\.)?(.+)'
    replacement: "https://${1}"
    permanent: true
